INSERT INTO "APEX_RELEASE" (
  "VERSION_NO"
 ,"API_COMPATIBILITY"
 ,"PATCH_APPLIED"
) VALUES (
  '5.0.1'
 ,'2013.01.01'
 ,NULL
);
INSERT INTO "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"
 ,"WORKSPACE_NAME"
 ,"SCHEMA"
) VALUES (
  1
 ,'DEVELOPMENT'
 ,'PUBLIC'
);
INSERT INTO "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"
 ,"WORKSPACE_NAME"
 ,"SCHEMA"
) VALUES (
  1
 ,'DEVELOPMENT'
 ,'OTHER'
);
INSERT INTO "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"
 ,"WORKSPACE_NAME"
 ,"SCHEMA"
) VALUES (
  2
 ,'PRODUCTION'
 ,'OTHER'
);
