INSERT INTO "APEX_RELEASE" (
  "VERSION_NO"
 ,"API_COMPATIBILITY"
 ,"PATCH_APPLIED"
) VALUES (
  '5.0.1'
 ,'2013.01.01'
 ,NULL
);
INSERT INTO "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"
 ,"WORKSPACE_NAME"
 ,"SCHEMA"
) VALUES (
  1
 ,'DEVELOPMENT'
 ,'PUBLIC'
);
INSERT INTO "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"
 ,"WORKSPACE_NAME"
 ,"SCHEMA"
) VALUES (
  1
 ,'DEVELOPMENT'
 ,'OTHER'
);
INSERT INTO "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"
 ,"WORKSPACE_NAME"
 ,"SCHEMA"
) VALUES (
  2
 ,'PRODUCTION'
 ,'OTHER'
);
INSERT INTO "APEX_APPLICATIONS" (
  "APPLICATION_ID"
) VALUES (
  103
);
INSERT INTO "SESSION_PRIVS" (
  "PRIVILEGE"
) VALUES (
  'ALTER ANY TABLE'
);
INSERT INTO "SESSION_PRIVS" (
  "PRIVILEGE"
) VALUES (
  'CREATE ANY TABLE'
);
INSERT INTO "SESSION_PRIVS" (
  "PRIVILEGE"
) VALUES (
  'DROP ANY TABLE'
);
INSERT INTO "ALL_TABLES" (
  "OWNER"
 ,"TABLE_NAME"
) VALUES (
  'PUBLIC'
 ,'DATABASECHANGELOG'
);
INSERT INTO "USER_TABLES" (
  "TABLE_NAME"
) VALUES (
  'DATABASECHANGELOG'
);
INSERT INTO "SESSION_ROLES" (
  "ROLE"
) VALUES (
  'APEX_ADMINISTRATOR_ROLE'
);