CREATE TABLE "APEX_RELEASE" (
  "VERSION_NO"        VARCHAR(4000)
 ,"API_COMPATIBILITY" VARCHAR(4000)
 ,"PATCH_APPLIED"     VARCHAR(4000)
);
CREATE TABLE "APEX_WORKSPACE_SCHEMAS" (
  "WORKSPACE_ID"   INTEGER
 ,"WORKSPACE_NAME" VARCHAR(255)
 ,"SCHEMA"         VARCHAR(128)
);
CREATE TABLE "APEX_APPLICATIONS" (
  "APPLICATION_ID" INTEGER
);
